/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Desktop;

/**
 *
 * @author geoffrey
 */
public class Reponse extends javax.swing.JFrame {

    /**
     * Creates new form Reponse
     */
    
    public Reponse() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        Next_Button = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(970, 680));
        setSize(new java.awt.Dimension(970, 680));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setText("FlashQuizz - Réponse ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(320, 10, 467, 51);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Desktop/images.jpeg"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 70, 265, 189);

        jTextField1.setBackground(java.awt.Color.lightGray);
        jTextField1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTextField1.setText("La réponse a la question : Réponse B .");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(50, 370, 320, 90);

        jTextField2.setBackground(java.awt.Color.lightGray);
        jTextField2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTextField2.setText("Il y a 50% des votant qui on répondu comme vous .");
        getContentPane().add(jTextField2);
        jTextField2.setBounds(370, 130, 555, 73);

        Next_Button.setBackground(java.awt.Color.white);
        Next_Button.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Next_Button.setText("NEXT->");
        Next_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Next_ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(Next_Button);
        Next_Button.setBounds(790, 570, 130, 50);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void Next_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Next_ButtonActionPerformed
        // TODO add your handling code here:
          
        switch (variable.var)
            
        {
            
            case 1:{
                variable.var = 2;
            Radio radio = new Radio();
           radio.setVisible(true);
           (this).setVisible(false);
           break;
          }
            case 2: {
            variable.var = 3;
             Texte texte = new Texte();
           texte.setVisible(true);
           (this).setVisible(false);
            break;
           }
            
           case 3:{
               variable.var = 4;
             Checkbox check = new Checkbox();
           check.setVisible(true);
           (this).setVisible(false);
            break;
           }
           
           case 4: {
                 variable.var = 5;
             Radio rad = new Radio();
           rad.setVisible(true);
           (this).setVisible(false);
            break;
           }
             case 5: {
                 variable.var = 1;
             Recap rec = new Recap();
           rec.setVisible(true);
           (this).setVisible(false);
            break;
           }
        
    }//GEN-LAST:event_Next_ButtonActionPerformed

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Next_Button;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
